import { Layout } from '@/components/Layout';
import '@/styles/globals.css';
import { EmotionCache } from '@emotion/react';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { SessionProvider } from 'next-auth/react';
import type { AppProps } from 'next/app';

interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache;
}

import createCache from '@emotion/cache';
import { CacheProvider } from "@emotion/react";
import { LocalizationProvider } from '@mui/x-date-pickers';
import Head from 'next/head';

function createEmotionCache() {
  return createCache({ key: 'css', prepend: true });
}

const clientSideEmotionCache = createEmotionCache();

export default function App({ Component, pageProps, emotionCache = clientSideEmotionCache }: MyAppProps) {

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <CacheProvider value={emotionCache}>
        <SessionProvider session={pageProps.session}>
          <Layout>
            <Head>
              <title>BZ Commendations</title>
              <link rel="shortcut icon" href="/favicon.png" />
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Component {...pageProps} />
          </Layout>
        </SessionProvider>
      </CacheProvider>
    </LocalizationProvider>
  )
}